# Generated by Django 3.1 on 2022-03-14 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePanier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('ordered', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article du panier',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desigantion', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('sous_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categories')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='ConditionLivraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livraison', models.CharField(blank=True, max_length=200, null=True)),
                ('autres', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condition de livraison',
                'verbose_name_plural': 'Conditions de livraison',
            },
        ),
        migrations.CreateModel(
            name='ConditionPaiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiement', models.CharField(blank=True, max_length=200, null=True)),
                ('autres', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condition de paiement',
                'verbose_name_plural': 'Conditions de paiement',
            },
        ),
        migrations.CreateModel(
            name='CondtionDeRetour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retour', models.CharField(blank=True, max_length=200, null=True)),
                ('autres', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condition de retour',
                'verbose_name_plural': 'Conditions de retour',
            },
        ),
        migrations.CreateModel(
            name='Couleurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('code_couleur', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('couleur_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Tag de produit',
                'verbose_name_plural': 'Tags des produits',
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'matériel',
                'verbose_name_plural': 'matériaux',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('longue_description', models.TextField(blank=True, max_length=600, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('prix', models.FloatField(blank=True, null=True)),
                ('prix_promo', models.FloatField(blank=True, null=True)),
                ('fabricant', models.CharField(blank=True, max_length=100, null=True)),
                ('mise_en_avant', models.BooleanField(blank=True, default=False, null=True)),
                ('af_du_jour', models.BooleanField(blank=True, default=False, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('longeur', models.FloatField(blank=True, null=True)),
                ('largeur', models.FloatField(blank=True, null=True)),
                ('hauteur', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='core.Categories')),
                ('condition_livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.conditionlivraison')),
                ('condition_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.conditionpaiement')),
                ('condition_retour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.condtionderetour')),
                ('couleurs', models.ManyToManyField(blank=True, to='core.Couleurs')),
                ('label', models.ManyToManyField(blank=True, to='core.LabelProduit')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.marque')),
                ('materiel', models.ManyToManyField(blank=True, to='core.Materiel')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitWishliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article wishliste',
                'verbose_name_plural': 'Articles wishliste',
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewsPorduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Vue récemmment',
            },
        ),
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'taille',
                'verbose_name_plural': 'tailles',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ManyToManyField(blank=True, null=True, to='core.ProduitWishliste')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Liste d'envies",
                'verbose_name_plural': "listes d'envies",
            },
        ),
        migrations.CreateModel(
            name='RecentlyViwed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ManyToManyField(blank=True, null=True, to='core.RecentlyViewsPorduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liste Artcile vue récemment',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_identification', models.CharField(blank=True, max_length=40, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('code_access', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='taille',
            field=models.ManyToManyField(blank=True, to='core.Taille'),
        ),
        migrations.CreateModel(
            name='ProductImageVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
            options={
                'verbose_name': 'Variation de produit',
                'verbose_name_plural': 'Variations des produits',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('adresse_livraison', models.CharField(blank=True, max_length=1000, null=True)),
                ('mode_paiement', models.CharField(blank=True, choices=[('liv', 'Paiement à la livraison'), ('rib', 'Virement Bancaire'), ('ccp', 'Virement CCP')], max_length=3, null=True)),
                ('frais_livraison', models.FloatField(blank=True, null=True)),
                ('ordered', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, null=True, to='core.ArticlePanier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='CommentairesProduits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaires', models.TextField(blank=True, max_length=1000, null=True)),
                ('nom_client', models.CharField(blank=True, max_length=100, null=True)),
                ('email_client', models.EmailField(blank=True, max_length=1000, null=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
            options={
                'verbose_name': 'Commentaire produit',
                'verbose_name_plural': 'Commentaires produits',
            },
        ),
        migrations.CreateModel(
            name='CollectionProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ManyToManyField(blank=True, to='core.Produit')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Colléctions',
            },
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produit'),
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AffaireDuJour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_aff_du_jour', models.BooleanField(blank=True, default=False, null=True)),
                ('is_mise_avant', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.produit')),
            ],
        ),
    ]
