# Generated by Django 3.1 on 2022-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('rib', 'Virement Bancaire'), ('liv', 'Paiement à la livraison'), ('ccp', 'Virement CCP')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='panier',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
