# Generated by Django 3.1.4 on 2021-08-11 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_condtionderetour'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='condition_retour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.condtionderetour'),
        ),
    ]
