# Generated by Django 3.1.4 on 2021-08-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produit_condition_retour'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ManyToManyField(blank=True, to='core.Produit')),
            ],
            options={
                'verbose_name': ('Collection',),
                'verbose_name_plural': 'Colléctions',
            },
        ),
    ]
