# Generated by Django 3.1 on 2022-03-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220314_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepanier',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='panier',
            name='articles',
            field=models.ManyToManyField(to='core.ArticlePanier'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('rib', 'Virement Bancaire'), ('ccp', 'Virement CCP'), ('liv', 'Paiement à la livraison')], max_length=3, null=True),
        ),
    ]
