# Generated by Django 3.1 on 2022-03-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220314_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimagevariation',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimagevariation',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productimagevariation',
            name='image3',
        ),
        migrations.AlterField(
            model_name='panier',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('ccp', 'Virement CCP'), ('rib', 'Virement Bancaire'), ('liv', 'Paiement à la livraison')], max_length=3, null=True),
        ),
    ]
