# Generated by Django 3.1 on 2022-03-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220314_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monnaie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'Monnaie',
                'verbose_name_plural': 'Monnaies',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=40, null=True)),
                ('code_court', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.AlterField(
            model_name='panier',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('liv', 'Paiement à la livraison'), ('ccp', 'Virement CCP'), ('rib', 'Virement Bancaire')], max_length=3, null=True),
        ),
    ]
