# Generated by Django 3.1.4 on 2021-08-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210812_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Taille',
                'verbose_name_plural': 'Tailles',
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='hauteur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='largeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='longeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='taille',
            field=models.ManyToManyField(blank=True, to='core.Taille'),
        ),
    ]
