# Generated by Django 3.1.4 on 2021-08-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210812_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'matériel',
                'verbose_name_plural': 'matériaux',
            },
        ),
        migrations.AlterModelOptions(
            name='taille',
            options={'verbose_name': 'taille', 'verbose_name_plural': 'tailles'},
        ),
        migrations.AddField(
            model_name='produit',
            name='materiel',
            field=models.ManyToManyField(blank=True, to='core.Materiel'),
        ),
    ]
