# Generated by Django 3.1.4 on 2021-08-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210813_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('couleur_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Tag de produit',
                'verbose_name_plural': 'Tags des produits',
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='label',
            field=models.ManyToManyField(blank=True, to='core.LabelProduit'),
        ),
    ]
