# Generated by Django 3.1 on 2022-03-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220314_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('liv', 'Paiement à la livraison'), ('rib', 'Virement Bancaire'), ('ccp', 'Virement CCP')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('cli', 'Client'), ('adm', 'Administrateur')], max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
