# Generated by Django 3.1.4 on 2021-08-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210816_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='longue_description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
